#!/usr/bin/env bash
# script that transfers a file from our client to a server

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

FILE_TO_COPY="$1"
IP="$2"
USERNAME="$3"
FILE_KEY_SSH="$4"

if [ -f "$FILE_KEY_SSH" ]; then
    scp -o  StrictHostKeyChecking=no -i "$FILE_KEY_SSH" "$FILE_TO_COPY" "${USERNAME}@${IP}":~/
fi
