#!/usr/bin/env bash
# Bash script that displays Holberton School 10 times with while loop
var="Holberton School"

i=0
while [ $i -lt 10 ]; do
        if [ $i -eq 3 ]
        then
                echo "bad luck"
        elif [ $i -eq 7 ]
        then
                echo "good luck"
        else
                echo "$var"
        fi
        ((i = i + 1))
done
